language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - 2.1.2
  - 2.2.0-preview1
cache: bundler
after_success:
  - bundle exec inch
  - bundle exec rubocop

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.2.0-preview1
